### ISSUE TITLE
用python3 -m playwright install 无反应，用python -m playwright install安装后报错

### ISSUE THREAD

**Issue by jjjyyyllll** [kerms5/book118#4]

**Comment by jjjyyyllll** [comment]
PS D:\SoftWares\book118> python run.py 'https://max.book118.com/html/2022/0223/7111013165004065.shtm'
Traceback (most recent call last):
  File "D:\SoftWares\book118\run.py", line 231, in <module>
    run(playwright)
  File "D:\SoftWares\book118\run.py", line 12, in run
    browser = playwright.chromium.launch(headless=False)
  File "D:\SoftWares\Python\lib\site-packages\playwright\sync_api\_generated.py", line 11511, in launch
    self._sync(
  File "D:\SoftWares\Python\lib\site-packages\playwright\_impl\_sync_base.py", line 88, in _sync
    return task.result()
  File "D:\SoftWares\Python\lib\site-packages\playwright\_impl\_browser_type.py", line 90, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "D:\SoftWares\Python\lib\site-packages\playwright\_impl\_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "D:\SoftWares\Python\lib\site-packages\playwright\_impl\_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Executable doesn't exist at C:\Users\Gudy\AppData\Local\ms-playwright\chromium-1000\chrome-win\chrome.exe
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     playwright install                                                  ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚═════════════════════════════════════════════════════════════════════════╝

**Comment by wbhinspector** [comment]
用playwright install安装

**Comment by kerms5** [comment]
嗯对

**Comment by AoiMatsu** [comment]
我也是这个问题，求解
Traceback (most recent call last):
  File "E:\Tem_lqs\book118-master\run.py", line 340, in <module>
    run(playwright)
  File "E:\Tem_lqs\book118-master\run.py", line 23, in run
    page.goto(url)
  File "D:\python_lqs\lib\site-packages\playwright\sync_api\_generated.py", line 7413, in goto
    self._sync(
  File "D:\python_lqs\lib\site-packages\playwright\_impl\_sync_base.py", line 88, in _sync
    return task.result()
  File "D:\python_lqs\lib\site-packages\playwright\_impl\_page.py", line 493, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "D:\python_lqs\lib\site-packages\playwright\_impl\_frame.py", line 122, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "D:\python_lqs\lib\site-packages\playwright\_impl\_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "D:\python_lqs\lib\site-packages\playwright\_impl\_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Protocol error (Page.navigate): Cannot navigate to invalid URL
=========================== logs ===========================
navigating to "'https://max.book118.com/html/2016/0702/47078219.shtm'", waiting until "load"
============================================================

**Comment by AoiMatsu** [comment]
我也是这个问题，请问大佬有解决吗？

**Comment by kerms5** [comment]
运行 `playwright install`

**Comment by zzpop** [comment]
只能说控制台都提示你了
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers: ║
║ ║
║ playwright install ║
║ ║
║ <3 Playwright Team ║
╚═════════════════════════════════════════════════════════════════════════╝
意思是你需要先运行 playwright install
